### ISSUE TITLE
[ENHANCEMENT] hovering over white space triggers 'admin user' dropdown 

### ISSUE THREAD

**Issue by hukellyy** [calblueprint/ogsc#216]
**Is your enhancement request related to a problem related to existing functionality or ux/ui? Please describe.**
existing functionality - hovering over the space beside the admin user button triggers the dropdown menu, which gets in the way if i want to click on stuff in the main panel. 

**Describe the solution you'd like to see**
fixing the hover space so that it's only on the grey area and not the white

**Additional context**
Provide any additional screenshots that would be helpful here
![IMG_1517](https://user-images.githubusercontent.com/77181350/115129506-7664d900-9f9b-11eb-9f71-cd632b34cd63.JPG)
<img width="547" alt="Screen Shot 2021-04-17 at 4 29 14 PM" src="https://user-images.githubusercontent.com/77181350/115129510-7e247d80-9f9b-11eb-9cda-b65b167d2753.png">

@sydbui

**Comment by ethanlee16** [comment]
Good catch. 

@sydbui @rlhe811 My sense here is that we should consider making this whole row (the group that displays name + email + picture) hoverable but only show `cursor: pointer` and a slightly tinted backdrop. Then, a click on the row would cause the popover to display to the side as it does now. The hover is a little too jarring IMO.
