### ISSUE TITLE
[BUG] Undefined mile time error handling

### ISSUE THREAD

**Issue by cnnmon** [calblueprint/ogsc#225]
**Describe the bug: What happened?**
If you don't input a mile time, the mile time shows up as "undefined minutes undefined seconds".

**url or screen that error occurred?**
https://ogsc-deploy.herokuapp.com/admin/players/157

**To Reproduce Bug**
If possible, please provide steps to reproduce the bug that you saw

1. Go to Sydney (https://ogsc-deploy.herokuapp.com/admin/players/157)
2. Go to physical wellness & view 1 mile time

Alternatively:
1. Create a new player
2. Don't input mile time
3. View profile

**Expected behavior?**
The field should probably be omitted entirely or "undefined minutes undefined seconds" should be instead left blank.

**Screenshots**
![image](https://user-images.githubusercontent.com/20329981/115129966-fe4ce200-9f9f-11eb-9bd6-fae636000315.png)

**Environment (please complete the following information):**
Which environment(s) is this bug located in?

- local [localhost:port]
- local or dev [review-app.heroku.com]
- stage [stage-app-name.heroku.com]
- production [www.application.com]

**Additional information**
Is there additional information you can provide?

cc: @pl

**Comment by ethanlee16** [comment]
Thanks for the report - closing this one, as this profile is using an old format for storing this field and should've been removed beforehand. We don't anticipate that profiles will be shaped like this user's in production.
